name: gcp

on:
  push:

jobs:
  gsls:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/causal-analyst-402006/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'github-actions@causal-analyst-402006.iam.gserviceaccount.com'

      # プライベートな GCS バケットを読み取ってみる
      - run: gcloud storage ls gs://oidc-test-bucket-example
